"""Create NetworkDetails table

Revision ID: 261e2a84fad5
Revises: 9c0d59202996
Create Date: 2023-12-09 11:09:27.849078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261e2a84fad5'
down_revision = '9c0d59202996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('link_speed', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_details')
    # ### end Alembic commands ###
