"""Initial migration

Revision ID: 9c0d59202996
Revises: 
Create Date: 2023-11-23 21:09:42.906861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d59202996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_ip', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('dst_ip', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('src_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dst_port', sa.Integer(), nullable=True))
        batch_op.drop_column('destination_ip')
        batch_op.drop_column('destination_port')
        batch_op.drop_column('source_port')
        batch_op.drop_column('source_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_ip', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('source_port', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('destination_port', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('destination_ip', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('dst_port')
        batch_op.drop_column('src_port')
        batch_op.drop_column('dst_ip')
        batch_op.drop_column('src_ip')

    # ### end Alembic commands ###
